name = "shopify-order-status"
main = "index.js"
compatibility_date = "2024-10-11"

[vars]
SHOPIFY_API_VERSION = "2024-10"

# Native Cloudflare Rate Limiting
[[ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 60, period = 60 }

# Secrets (set via CLI):
# wrangler secret put API_KEY
# wrangler secret put SHOPIFY_STORE_URL_DE
# wrangler secret put SHOPIFY_ACCESS_TOKEN_DE
# ... repeat for CH, AT, IT, FR, NL

